# POST http://localhost:4000/app/signup
# Content-Type: application/json

# {
#     "fullname": "Aryan Singh",
#     "username": "aryansingh920",
#     "email": "aryansingh920@outlook",
#     "password": "password"
# }

GET http://localhost:4000/app/addedUser